name: kalender
description: This Flutter package offers a Calendar Widget featuring Day, MultiDay, Month and Schedule views. Moreover, it empowers you to tailor the visual aspects of the calendar widget.
version: 0.11.0
repository: https://github.com/werner-scholtz/kalender.git
topics: 
  - calendar
  - widget

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  intl: '>=0.17.0 <0.23.0'
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  timezone: ^0.9.2
